#! /bin/bash
#ZF30  
/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF30-DS5.realigned.barcoded.bam.family.bam O= ZF30-DS5.dge.newannot.txt.gz \
SUMMARY=ZF30-DS5.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=625 MIN_NUM_READS_PER_CELL=1000 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF30-DS5b.realigned.barcoded.bam.family.bam O= ZF30-DS5b.dge.newannot.txt.gz \
SUMMARY=ZF30-DS5b.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=625 MIN_NUM_READS_PER_CELL=1000 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

#ZF3S
/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF3S-DS5.realigned.barcoded.bam.family.bam O= ZF3S-DS5.dge.newannot.txt.gz \
SUMMARY=ZF3S-DS5.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=500 MIN_NUM_READS_PER_CELL=1000 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

#ZF50
/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF50-DS2.realigned.barcoded.bam.family.bam O= ZF50-DS2.dge.newannot.txt.gz \
SUMMARY=ZF50-DS2.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=600 MIN_NUM_READS_PER_CELL=1500 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF50-DS3.realigned.barcoded.bam.family.bam O= ZF50-DS3.dge.newannot.txt.gz \
SUMMARY=ZF50-DS3.summary.newannot.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=600 MIN_NUM_READS_PER_CELL=1500 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF50-DS4.realigned.barcoded.bam.family.bam O= ZF50-DS4.dge.newannot.txt.gz \
SUMMARY=ZF50-DS4.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=600 MIN_NUM_READS_PER_CELL=1500 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF50-DS4b.realigned.barcoded.bam.family.bam O= ZF50-DS4b.dge.newannot.txt.gz \
SUMMARY=ZF50-DS4b.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=600 MIN_NUM_READS_PER_CELL=1500 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

#ZF60
/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF60-DS2.realigned.barcoded.bam.family.bam O= ZF60-DS2.dge.newannot.txt.gz \
SUMMARY=ZF60-DS2.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=600 MIN_NUM_READS_PER_CELL=1500 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF60-DS3.realigned.barcoded.bam.family.bam O= ZF60-DS3.dge.newannot.txt.gz \
SUMMARY=ZF60-DS3.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=600 MIN_NUM_READS_PER_CELL=1500 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF60-DS4.realigned.barcoded.bam.family.bam O= ZF60-DS4.dge.newannot.txt.gz \
SUMMARY=ZF60-DS4.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=600 MIN_NUM_READS_PER_CELL=1500 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

#ZF6S
/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF6S-DS5.realigned.barcoded.bam.family.bam O= ZF6S-DS5.dge.newannot.txt.gz \
SUMMARY=ZF6S-DS5.summary.newannot.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=500 MIN_NUM_READS_PER_CELL=1000 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF6S-DS5b.realigned.barcoded.bam.family.bam O= ZF6S-DS5b.dge.newannot.txt.gz \
SUMMARY=ZF6S-DS5b.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=500 MIN_NUM_READS_PER_CELL=1000 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

#ZF75
/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF75-DS2.realigned.barcoded.bam.family.bam O= ZF75-DS2.dge.newannot.txt.gz \
SUMMARY=ZF75-DS2.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=600 MIN_NUM_READS_PER_CELL=1400 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF75-DS3.realigned.barcoded.bam.family.bam O= ZF75-DS3.dge.newannot.txt.gz \
SUMMARY=ZF75-DS3.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=600 MIN_NUM_READS_PER_CELL=1400 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF75-DS4.realigned.barcoded.bam.family.bam O= ZF75-DS4.dge.newannot.txt.gz \
SUMMARY=ZF75-DS4.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=600 MIN_NUM_READS_PER_CELL=1400 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

#ZF90
/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF90-DS2.realigned.barcoded.bam.family.bam O= ZF90-DS2.dge.newannot.txt.gz \
SUMMARY=ZF90-DS2.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=500 MIN_NUM_READS_PER_CELL=1000 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF90-DS3.realigned.barcoded.bam.family.bam O= ZF90-DS3.dge.newannot.txt.gz \
SUMMARY=ZF90-DS3.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=500 MIN_NUM_READS_PER_CELL=1000 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF90-DS4.realigned.barcoded.bam.family.bam O= ZF90-DS4.dge.newannot.txt.gz \
SUMMARY=ZF90-DS4.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=500 MIN_NUM_READS_PER_CELL=1000 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE
