#! /bin/bash
#ZF30  
/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF30-DS5.realigned.barcoded.bam.family.bam O= ZF30-DS5.dge.newannot.txt.gz \
SUMMARY=ZF30-DS5.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=625 MIN_NUM_READS_PER_CELL=1000 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF30-DS5b.realigned.barcoded.bam.family.bam O= ZF30-DS5b.dge.newannot.txt.gz \
SUMMARY=ZF30-DS5b.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=625 MIN_NUM_READS_PER_CELL=1000 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

#ZF3S
/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF3S-DS5.realigned.barcoded.bam.family.bam O= ZF3S-DS5.dge.newannot.txt.gz \
SUMMARY=ZF3S-DS5.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=500 MIN_NUM_READS_PER_CELL=1000 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

#ZF50
/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF50-DS2.realigned.barcoded.bam.family.bam O= ZF50-DS2.dge.newannot.txt.gz \
SUMMARY=ZF50-DS2.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=600 MIN_NUM_READS_PER_CELL=1500 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF50-DS3.realigned.barcoded.bam.family.bam O= ZF50-DS3.dge.newannot.txt.gz \
SUMMARY=ZF50-DS3.summary.newannot.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=600 MIN_NUM_READS_PER_CELL=1500 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF50-DS4.realigned.barcoded.bam.family.bam O= ZF50-DS4.dge.newannot.txt.gz \
SUMMARY=ZF50-DS4.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=600 MIN_NUM_READS_PER_CELL=1500 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF50-DS4b.realigned.barcoded.bam.family.bam O= ZF50-DS4b.dge.newannot.txt.gz \
SUMMARY=ZF50-DS4b.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=600 MIN_NUM_READS_PER_CELL=1500 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

#ZF60
/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF60-DS2.realigned.barcoded.bam.family.bam O= ZF60-DS2.dge.newannot.txt.gz \
SUMMARY=ZF60-DS2.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=600 MIN_NUM_READS_PER_CELL=1500 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF60-DS3.realigned.barcoded.bam.family.bam O= ZF60-DS3.dge.newannot.txt.gz \
SUMMARY=ZF60-DS3.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=600 MIN_NUM_READS_PER_CELL=1500 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF60-DS4.realigned.barcoded.bam.family.bam O= ZF60-DS4.dge.newannot.txt.gz \
SUMMARY=ZF60-DS4.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=600 MIN_NUM_READS_PER_CELL=1500 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

#ZF6S
/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF6S-DS5.realigned.barcoded.bam.family.bam O= ZF6S-DS5.dge.newannot.txt.gz \
SUMMARY=ZF6S-DS5.summary.newannot.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=500 MIN_NUM_READS_PER_CELL=1000 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF6S-DS5b.realigned.barcoded.bam.family.bam O= ZF6S-DS5b.dge.newannot.txt.gz \
SUMMARY=ZF6S-DS5b.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=500 MIN_NUM_READS_PER_CELL=1000 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

#ZF75
/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF75-DS2.realigned.barcoded.bam.family.bam O= ZF75-DS2.dge.newannot.txt.gz \
SUMMARY=ZF75-DS2.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=600 MIN_NUM_READS_PER_CELL=1400 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF75-DS3.realigned.barcoded.bam.family.bam O= ZF75-DS3.dge.newannot.txt.gz \
SUMMARY=ZF75-DS3.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=600 MIN_NUM_READS_PER_CELL=1400 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF75-DS4.realigned.barcoded.bam.family.bam O= ZF75-DS4.dge.newannot.txt.gz \
SUMMARY=ZF75-DS4.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=600 MIN_NUM_READS_PER_CELL=1400 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

#ZF90
/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF90-DS2.realigned.barcoded.bam.family.bam O= ZF90-DS2.dge.newannot.txt.gz \
SUMMARY=ZF90-DS2.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=500 MIN_NUM_READS_PER_CELL=1000 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF90-DS3.realigned.barcoded.bam.family.bam O= ZF90-DS3.dge.newannot.txt.gz \
SUMMARY=ZF90-DS3.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=500 MIN_NUM_READS_PER_CELL=1000 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZF90-DS4.realigned.barcoded.bam.family.bam O= ZF90-DS4.dge.newannot.txt.gz \
SUMMARY=ZF90-DS4.newannot.summary.txt TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 \
MIN_NUM_GENES_PER_CELL=500 MIN_NUM_READS_PER_CELL=1000 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

#! /bin/bash

#ZFB
/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZFB-DS2.realigned.barcoded.bam.family.bam O= ZFB-DS2.dge.newannot.txt.gz SUMMARY=ZFB-DS2.newannot.summary.txt \
TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 MIN_NUM_GENES_PER_CELL=500 MIN_NUM_READS_PER_CELL=1000 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE 

/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZFB-DS2b.realigned.barcoded.bam.family.bam O= ZFB-DS2b.dge.newannot.txt.gz SUMMARY=ZFB-DS2b.newannot.summary.txt \
TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 MIN_NUM_GENES_PER_CELL=500 MIN_NUM_READS_PER_CELL=1000 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZFB-DS3.realigned.barcoded.bam.family.bam O= ZFB-DS3.dge.newannot.txt.gz SUMMARY=ZFB-DS3.newannot.summary.txt \
TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 MIN_NUM_GENES_PER_CELL=500 MIN_NUM_READS_PER_CELL=1000 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZFB-DS4.realigned.barcoded.bam.family.bam O= ZFB-DS4.dge.newannot.txt.gz SUMMARY=ZFB-DS4.newannot.summary.txt \
TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 MIN_NUM_GENES_PER_CELL=500 MIN_NUM_READS_PER_CELL=1000 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

#ZFDOME
/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZFDOME-DS5.realigned.barcoded.bam.family.bam O= ZFDOME-DS5.dge.newannot.txt.gz SUMMARY=ZFDOME-DS5.newannot.summary.txt \
TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 MIN_NUM_GENES_PER_CELL=800 MIN_NUM_READS_PER_CELL=2000 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

#ZFHIGH
/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZFHIGH-DS5.realigned.barcoded.bam.family.bam O= ZFHIGH-DS5.dge.newannot.txt.gz SUMMARY=ZFHIGH-DS5.newannot.summary.txt \
TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 MIN_NUM_GENES_PER_CELL=1000 MIN_NUM_READS_PER_CELL=1500 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZFHIGH-DS5b.realigned.barcoded.bam.family.bam O= ZFHIGH-DS5b.dge.newannot.txt.gz SUMMARY=ZFHIGH-DS5b.newannot.summary.txt \
TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 MIN_NUM_GENES_PER_CELL=1000 MIN_NUM_READS_PER_CELL=1500 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

#ZFOBLONG
/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZFOBLONG-DS5.realigned.barcoded.bam.family.bam O= ZFOBLONG-DS5.dge.newannot.txt.gz SUMMARY=ZFOBLONG-DS5.newannot.summary.txt \
TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 MIN_NUM_GENES_PER_CELL=625 MIN_NUM_READS_PER_CELL=1500 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZFOBLONG-DS5b.realigned.barcoded.bam.family.bam O= ZFOBLONG-DS5b.dge.newannot.txt.gz SUMMARY=ZFOBLONG-DS5b.newannot.summary.txt \
TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 MIN_NUM_GENES_PER_CELL=625 MIN_NUM_READS_PER_CELL=1500 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

#ZFS
/workdir/nc499/tools/Drop-seq_tools-2.3.0/DigitalExpression -m 120g \
I=ZFS-DS5.realigned.barcoded.bam.family.bam O= ZFS-DS5.dge.newannot.txt.gz SUMMARY=ZFS-DS5.newannot.summary.txt \
TMP_DIR=/workdir/nc499/temp/ READ_MQ= -1 MIN_NUM_GENES_PER_CELL=600 MIN_NUM_READS_PER_CELL=1000 USE_STRAND_INFO=false STRAND_STRATEGY=SENSE

###################################################
#create an informative header
#! /bin/bash
sed -i -e '1s/\t/\tZF30-DS5_/g'	ZF30-DS5.dge.newannot.txt 
sed -i -e '1s/\t/\tZF30-DS5b_/g'    ZF30-DS5b.dge.newannot.txt
sed -i -e '1s/\t/\tZF3S-DS5_/g'	ZF3S-DS5.dge.newannot.txt 
sed -i -e '1s/\t/\tZF50-DS2_/g'	ZF50-DS2.dge.newannot.txt 
sed -i -e '1s/\t/\tZF50-DS3_/g'	ZF50-DS3.dge.newannot.txt 
sed -i -e '1s/\t/\tZF50-DS4_/g'	ZF50-DS4.dge.newannot.txt 
sed -i -e '1s/\t/\tZF50-DS4b_/g'	ZF50-DS4b.dge.newannot.txt
sed -i -e '1s/\t/\tZF60-DS2_/g'	ZF60-DS2.dge.newannot.txt 
sed -i -e '1s/\t/\tZF60-DS3_/g'	ZF60-DS3.dge.newannot.txt 
sed -i -e '1s/\t/\tZF60-DS4_/g'	ZF60-DS4.dge.newannot.txt 
sed -i -e '1s/\t/\tZF6S-DS5_/g'	ZF6S-DS5.dge.newannot.txt 
sed -i -e '1s/\t/\tZF6S-DS5b_/g'	ZF6S-DS5b.dge.newannot.txt
sed -i -e '1s/\t/\tZF75-DS2_/g'	ZF75-DS2.dge.newannot.txt 
sed -i -e '1s/\t/\tZF75-DS3_/g'	ZF75-DS3.dge.newannot.txt 
sed -i -e '1s/\t/\tZF75-DS4_/g'	ZF75-DS4.dge.newannot.txt 
sed -i -e '1s/\t/\tZF90-DS2_/g'	ZF90-DS2.dge.newannot.txt 
sed -i -e '1s/\t/\tZF90-DS3_/g'	ZF90-DS3.dge.newannot.txt 
sed -i -e '1s/\t/\tZF90-DS4_/g'	ZF90-DS4.dge.newannot.txt 
sed -i -e '1s/\t/\tZFB-DS2_/g'	ZFB-DS2.dge.newannot.txt
sed -i -e '1s/\t/\tZFB-DS2b_/g'	ZFB-DS2b.dge.newannot.txt
sed -i -e '1s/\t/\tZFB-DS3_/g'	ZFB-DS3.dge.newannot.txt
sed -i -e '1s/\t/\tZFB-DS4_/g'	ZFB-DS4.dge.newannot.txt
sed -i -e '1s/\t/\tZFDOME-DS5_/g'	ZFDOME-DS5.dge.newannot.txt
sed -i -e '1s/\t/\tZFHIGH-DS5_/g'	ZFHIGH-DS5.dge.newannot.txt
sed -i -e '1s/\t/\tZFHIGH-DS5b_/g'	ZFHIGH-DS5b.dge.newannot.txt
sed -i -e '1s/\t/\tZFOBLONG-DS5_/g'	ZFOBLONG-DS5.dge.newannot.txt
sed -i -e '1s/\t/\tZFOBLONG-DS5b_/g'	ZFOBLONG-DS5b.dge.newannot.txt
sed -i -e '1s/\t/\tZFS-DS5_/g'	ZFS-DS5.dge.newannot.txt

